### PR TITLE
Workaround to enable simd-accel feature to build on M1 macs

### PR DESCRIPTION
**Pull request by mvines**
I'm not particularly proud of this workaround, but I currently don't see a better way to get the `simd-accel` building on M1 macs.

Without this PR, I get this result on an M1 mac:
```
$ cargo build --features=simd-accel 
   Compiling reed-solomon-erasure v5.0.0 (/Users/mvines/ws/reed-solomon-erasure)
The following warnings were emitted during compilation:

warning: simd_c/reedsolomon.c:272:43: error: argument to '__builtin_neon_vshrq_n_v' must be a constant integer
warning:         const v128 result = { .uint8x16 = vshrq_n_u8(in.uint8x16, n) };
warning:                                           ^                       ~
warning: /Library/Developer/CommandLineTools/usr/lib/clang/13.0.0/include/arm_neon.h:25078:24: note: expanded from macro 'vshrq_n_u8'
warning:   __ret = (uint8x16_t) __builtin_neon_vshrq_n_v((int8x16_t)__s0, __p1, 48); \
warning:                        ^                                         ~~~~
warning: 1 error generated.
```

My cc:
```
$ /usr/bin/cc --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### CODE REVIEW

**Comment by mvines** [comment]
Hey @nazar-pc, does this error look familiar to you perchance?  I'm using a M1 MBP running Monterey.

**Comment by nazar-pc** [comment]
Maybe you can turn that function into macro, so it is always expanded with constants? BTW, looks like this was already discussed in #28

**Comment by mvines** [comment]
True, I did see that discussion. I shied away from that because:
1. I'm hoping that a future apple clang version will be smarter about optimizing that n = 4 away before hitting the intrinsic, like clearly the compilers for other platform already do, and then this commit just gets reverted.
2. `srli_epi64_v` has a number of ifdef'd implementations, and I'm worried about breaking one of them if I make a larger change here.

**Comment by nazar-pc** [comment]
At least a TODO is then required to explain why the argument is commented-out and defined inside of the function instead.

**Comment by mvines** [comment]
👍🏼 TODO added

**Review by nazar-pc — APPROVED** [review]

**Comment by mvines** [comment]
Thanks for the review

**Pull request merged**
